name: Build Standalone App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Extract Version from setup.py
      id: get_version
      run: |
        echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV

    - name: Build Application
      run: |
        pyinstaller --onefile -n tcia_download_manager tcia_download_manager/gui.py
      shell: bash

    - name: Upload Build Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: tcia_download_manager-windows-latest-v${{ env.VERSION }}
        path: dist/tcia_download_manager.exe

    - name: Upload Build Artifact (macOS and Ubuntu)
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: tcia_download_manager-${{ matrix.os }}-v${{ env.VERSION }}
        path: dist/tcia_download_manager
